routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin']], function(){
    Route::get('/admin', function () {
    return view('admin.dashboard'); 
});
Route::get('/addmembers', function(){
    return view('Memberview.add');
});
Route::get('/members', function(){
    return view('Memberview.index');
});
Route::get('/addallotment', function(){
    return view('layouts.Allotment.Add');
});
Route::get('/allotments', function(){
    return view('layouts.Allotment.Show');
});
Route::get('/addExpense', function(){
    return view('layouts.OfficeExpense.addExpense');
});
         //Resource Controller
Route::resource('members', 'MemberController');
Route::resource('allotments', 'AllotmentController');
Route::resource('expense', 'OfficeExpenseController');

  // end resource controller

//   Route::get('/profilepicture', 'ProfileController@changePasswordForm');
 
Route::get('/changePassword', 'ProfileController@changePasswordForm');
Route::post('/changepassword', 'ProfileController@updatePassword')->name('changePassword');
 
Route::get('/profile', 'ProfileController@profile')->name('profile');
Route::post('/profile', 'ProfileController@profileUpdate')->name('profileUpdate');

});

 

app/Allotment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Allotment extends Model
{
  protected $fillable =[
      'fullname', 
      'number',
      'cnic',
      'plotno',
      'block'
  ];
}

app/Http/Controllers/AllotmentController.php
<?php

namespace App\Http\Controllers;

use App\Allotment;
use Illuminate\Http\Request;

class AllotmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allotments = Allotment::latest()->paginate(5);
      return view('layouts.Allotment.Show',['allotments' => $allotments])
       ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('Allotment.Add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
  
        $validateData = $request->validate([
            'fullname' => 'required',
            'number' => 'required|numeric',
            'cnic' => 'required',
            'plotno' => 'required',
            'block' => 'required',
        ]);   
          $allotments = new Allotment();
         $allotments->fullname = $request->input('fullname');
        $allotments->number = $request->input('number');
        $allotments->cnic = $request->input('cnic');
        $allotments->plotno = $request->input('plotno');
        $allotments->block = $request->input('block');
          $allotments->save();
        return redirect('/allotments')->with('success', 'Successfully Added', $allotments);
 
     }

    /**
     * Display the specified resource.
     *
     * @param  \App\Allotment  $allotment
     * @return \Illuminate\Http\Response
     */
    public function show(Allotment $allotment)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Allotment  $allotment
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
         $allotments = Allotment::findOrFail($id);
              return view('layouts.Allotment.Editallotment', compact('allotments'));
             
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Allotment  $allotment
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Allotment $allotment)
    {
          $validateData = $request->validate([
            'fullname' => 'required',
            'number' => 'required|numeric',
            'cnic' => 'required',
            'plotno' => 'required',
            'block' => 'required',
        ]);
          $allotments = new Allotment();
         $allotments->fullname = $request->input('fullname');
        $allotments->number = $request->input('number');
        $allotments->cnic = $request->input('cnic');
        $allotments->plotno = $request->input('plotno');
        $allotments->block = $request->input('block');
          $allotments->save();
        return redirect('/allotments')->with('success', 'Successfully Added', $allotments);
 
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Allotment  $allotment
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
          $allotments = Allotment::find($id);
        $allotments->delete();
        return redirect('/allotments')->with('danger', 'Successfully  Deleted');
 
    }
}

resources/views/layouts/Allotment/Add.blade.php
@extends('layouts.master')

@section('title')

 Society Dashboard
@endsection

@section('content')
  <div class="container-fluid">
    
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Add Allotment</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                <li class="breadcrumb-item active">Add Allotment</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
 <section class="content">
        <div class="container-fluid">
        <form method="POST" action="{{route('allotments.store')}}" enctype="multipart/form-data">
           @csrf
               
    <div class="col">
        <label for="name">Full Name</label>
      <input type="text" name="fullname" class="form-control" placeholder="Full name">
    <span class="text-danger">{{$errors->first('fullname')}}</span>
    </div>
    <div class="col">
         <label for="number">Number</label>
      <input type="text" name="number" class="form-control" placeholder="Contact">
    <span class="text-danger">{{$errors->first('number')}}</span>
    </div>
      <div class="col">
         <label for="cnic">Cnic</label>
      <input type="text" name="cnic" class="form-control" placeholder="Cnic">
    <span class="text-danger">{{$errors->first('cnic')}}</span>
    </div>
  
 
    <div class="col">
        <label for="cnic">Plot No</label>
      <input type="text" name="plotno" class="form-control" placeholder="Enter Plot Number">
    <span class="text-danger">{{$errors->first('plotno')}}</span>
   
    </div>
    <div class="col">
         <label for="designation">Block</label>
         <select class="form-control" name="block"  >
      <option value="">Choose Block</option>
      <option value="A">A</option>
      <option value="B">B</option>
      <option value="C">C</option>
        <option value="D">D</option>
         </select>
     <span class="text-danger">{{$errors->first('block')}}</span>

    </div>
 

  <button type="submit" class="btn btn-primary mt-3">Submit</button>
</form>
         
        </div>
      </section>
@endsection


@section('scripts')
 <script src="plugins/jquery/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="plugins/jquery-ui/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- ChartJS -->
  <script src="plugins/chart.js/Chart.min.js"></script>
  <!-- Sparkline -->
  <script src="plugins/sparklines/sparkline.js"></script>
  <!-- JQVMap -->
  <script src="plugins/jqvmap/jquery.vmap.min.js"></script>
  <script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="plugins/jquery-knob/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="plugins/moment/moment.min.js"></script>
  <script src="plugins/daterangepicker/daterangepicker.js"></script>
  <!-- Tempusdominus Bootstrap 4 -->
  <script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
  <!-- Summernote -->
  <script src="plugins/summernote/summernote-bs4.min.js"></script>
  <!-- overlayScrollbars -->
  <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  <!-- AdminLTE App -->
  <script src="dist/js/adminlte.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="dist/js/pages/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="dist/js/demo.js"></script>
@endsection

resources/views/layouts/Allotment/Editallotment.blade.php
@extends('layouts.master')

@section('title')

 Society Dashboard
@endsection


@section('content')
 <div class="container-fluid">
    
          <div class="row mb-2">
            <div class="col-sm-6">
              <h1 class="m-0 text-dark">Edit Allotment</h1>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                <li class="breadcrumb-item active">Edit Allotment</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
        </div><!-- /.container-fluid -->
<section class="content">
     <div class="container-fluid">
     <form action="{{route('allotments.update', $allotment->id)}}" method="post" enctype="multipart/form-data">
          @csrf
           @method('PATCH')
               
    <div class="col">
        <label for="name">Full Name</label>
    <input type="text" name="fullname" value="{{$allotment->fullname}}" class="form-control" placeholder="Full name">
    <span class="text-danger">{{$errors->first('fullname')}}</span>
    </div>
    <div class="col">
         <label for="number">Number</label>
      <input type="text" name="number" value="{{$allotment->number}}" class="form-control" placeholder="Contact">
    <span class="text-danger">{{$errors->first('number')}}</span>
    </div>
  
 
  
            
    <div class="col">
        <label for="cnic">Cnic</label>
      <input type="text" name="cnic" value="{{$allotment->cnic}}" class="form-control" placeholder="Cnic Number">
    <span class="text-danger">{{$errors->first('cnic')}}</span>
   
    </div>
    <div class="col">
         <label for="block">block</label>
       <select class="form-control" name="block"  >
       <option value="{{$allotment->block}}">{{$allotment->block}}</option>
           <option value="A">A</option>
       <option value="B">B</option>
       <option value="C">C</option>
        <option value="D">D</option>
   
         </select>
     <span class="text-danger">{{$errors->first('block')}}</span>

    </div>
  

  <button type="submit" class="btn btn-primary mt-3">Update</button>
</form>
         </div>  
      </section>


@endsection
  @section('scripts')
 <script src="plugins/jquery/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="plugins/jquery-ui/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- ChartJS -->
  <script src="plugins/chart.js/Chart.min.js"></script>
  <!-- Sparkline -->
  <script src="plugins/sparklines/sparkline.js"></script>
  <!-- JQVMap -->
  <script src="plugins/jqvmap/jquery.vmap.min.js"></script>
  <script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="plugins/jquery-knob/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="plugins/moment/moment.min.js"></script>
  <script src="plugins/daterangepicker/daterangepicker.js"></script>
  <!-- Tempusdominus Bootstrap 4 -->
  <script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
  <!-- Summernote -->
  <script src="plugins/summernote/summernote-bs4.min.js"></script>
  <!-- overlayScrollbars -->
  <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  <!-- AdminLTE App -->
  <script src="dist/js/adminlte.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="dist/js/pages/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="dist/js/demo.js"></script>
@endsection

resources/views/layouts/Allotment/Show.blade.php
@extends('layouts.master')

@section('title')

 Society Dashboard
@endsection


@section('content')
 <div class="container-fluid">
     @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
    @if(session()->get('danger'))
    <div class="alert alert-danger">
      {{ session()->get('danger') }}  
    </div><br />
  @endif
  
          <div class="row mb-2">
            <div class="col-sm-6">
    <a href="/addallotment" class="btn btn-primary">Add Allotment</a>
            </div><!-- /.col -->
            <div class="col-sm-6">
              <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item"><a href="/admin">Home</a></li>
                <li class="breadcrumb-item active">Show Allotment</li>
              </ol>
            </div><!-- /.col -->
          </div><!-- /.row -->
           <table class="table m-2 table-bordered">
          {{-- <h1 align="center"> Total Data : <span id="total_records"></span></h1> --}}
        <thead class="thead-dark">
       <tr>
          <th >ID</th>
          <th>Name</th>
          <th>Contact</th>
          <th>Cnic</th>
          <th>Plot No</th>

          <th>Block</th>
        
          <th colspan = 2>Actions</th>
        
        </tr>
        </thead>
              <tbody>
     
        @foreach ($allotments as $key => $allotment)
       <tr>
        <td>{{$key + 1}}</td>
        <td>{{$allotment->fullname}}</td>
        <td>{{$allotment->number}}</td>
        <td>{{$allotment->cnic}}</td>
        <td>{{$allotment->plotno}}</td>
        <td>{{$allotment->block}}</td>
          <td>
          <a href="{{ route('allotments.edit', $allotment->id)}}" class="btn btn-primary">Edit</a>
            </td>
            <td>
                <form action="{{ route('allotments.destroy', $allotment->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
   
       </tr>
        @endforeach
    
         </tbody>
      
       
    </table>  
    {!! $allotments->links() !!}

  </div>
@endsection




  @section('scripts')
 <script src="plugins/jquery/jquery.min.js"></script>
  <!-- jQuery UI 1.11.4 -->
  <script src="plugins/jquery-ui/jquery-ui.min.js"></script>
  <!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
  <script>
    $.widget.bridge('uibutton', $.ui.button)
  </script>
  <!-- Bootstrap 4 -->
  <script src="plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
  <!-- ChartJS -->
  <script src="plugins/chart.js/Chart.min.js"></script>
  <!-- Sparkline -->
  <script src="plugins/sparklines/sparkline.js"></script>
  <!-- JQVMap -->
  <script src="plugins/jqvmap/jquery.vmap.min.js"></script>
  <script src="plugins/jqvmap/maps/jquery.vmap.usa.js"></script>
  <!-- jQuery Knob Chart -->
  <script src="plugins/jquery-knob/jquery.knob.min.js"></script>
  <!-- daterangepicker -->
  <script src="plugins/moment/moment.min.js"></script>
  <script src="plugins/daterangepicker/daterangepicker.js"></script>
  <!-- Tempusdominus Bootstrap 4 -->
  <script src="plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js"></script>
  <!-- Summernote -->
  <script src="plugins/summernote/summernote-bs4.min.js"></script>
  <!-- overlayScrollbars -->
  <script src="plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js"></script>
  <!-- AdminLTE App -->
  <script src="dist/js/adminlte.js"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="dist/js/pages/dashboard.js"></script>
  <!-- AdminLTE for demo purposes -->
  <script src="dist/js/demo.js"></script>
@endsection